### PR TITLE
Random status

### LINKED ISSUE #70: Random status (OK/BAD)
Hello,

Would be great to have an endpoint which will return random statuses.
For example:
/random/200-500
or /random?list=200,400,500
or /succces-or-failure (For ex.: 200 or 500)

### PR DESCRIPTION
**Pull request by neilboyd**
Fixes #70

`RandomSequenceGenerator` should really be two classes - a factory and an implementation - but I don't think it's worth the overhead

### CODE REVIEW

**Comment by aaronpowell** [comment]
I feel like this approach is a bit more complex than it needs to be. I'm not sure there's a lot of value in pulling the logic out to a separate service, as it's not like that service is an expensive object to create or contains a particularly expensive execution path. It'd be just as easy to pull the logic into the controller body and have it process there.

**Comment by neilboyd** [comment]
> I feel like this approach is a bit more complex than it needs to be. I'm not sure there's a lot of value in pulling the logic out to a separate service, as it's not like that service is an expensive object to create or contains a particularly expensive execution path. It'd be just as easy to pull the logic into the controller body and have it process there.

It seems like an ideal case for separation of concerns. I already made it less complex than it should really be, by not using the factory pattern.
I can try moving it into the controller, but I think the tests will be messier/more complex. The advantage of putting the randomness behind an interface is that you can make it predictable in tests, although tbh I didn't write tests that do that.

**Comment by aaronpowell** [comment]
Given that it's a randomness feature, testing for an exact match won't be logical because you'd achieve that by removing randomness from the execution engine.

And separation of concerns isn't a real factor here, it's really just working with the inbound URL segment, which I see no issue doing in a controller action.

**Comment by neilboyd** [comment]
I moved the code into the controller

**Comment by aaronpowell** [comment]
:shipit:

**Pull request merged**
