### PR TITLE
add test project

### PR DESCRIPTION
**Pull request by neilboyd**
Hi guys!
I made a test project for you. I hope you like it 😃 
It's not very extensive, but it's a start.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Thanks for tackling this, it's one of those things that I've being meaning to do, but never got around to.

I'd prefer we use https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing for the integration tests, rather than hit the Azure instance, as this way tests can be run _before_ deployment has happened.

The file `src/staging.runsettings` shouldn't be include, I'm assuming it's mainly there because it's relying on the Azure hosted resource.

Rather than creating a class for the status codes, I'd like to find a way that we can reuse the classes from the main web project, so we don't have the duplication of code.

**Comment by neilboyd** [comment]
> I'd prefer we use https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing for the integration tests, rather than hit the Azure instance, as this way tests can be run _before_ deployment has happened.

That's a good idea, but I don't think it excludes running against the deployment because things often work differently when deployed.

> The file `src/staging.runsettings` shouldn't be include, I'm assuming it's mainly there because it's relying on the Azure hosted resource.

I wasn't sure whether to include it. It's for running the tests locally and it saves everyone trying to figure out how to set it in case they want to run locally. I can remove it if you like.
Yes, it's for testing against the deployed resource, but as I said above, maybe it's a good idea to keep that (_as well as_ using 
`Microsoft.AspNetCore.Mvc.Testing`).
It's the same resource that's defined in `staging.yml`. BTW that was defined by you, but didn't exist, so I created it.

> Rather than creating a class for the status codes, I'd like to find a way that we can reuse the classes from the main web project, so we don't have the duplication of code.

That's possible, but then the tests are using the code that they're supposed to be testing, so if the code breaks then the tests will still pass because they're using the broken code.

**Comment by aaronpowell** [comment]
> > I'd prefer we use https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing for the integration tests, rather than hit the Azure instance, as this way tests can be run _before_ deployment has happened.
> 
> That's a good idea, but I don't think it excludes running against the deployment because things often work differently when deployed.

Since there's a self-hosted version (you can pull the container yourself), I more want to focus on testing the functionality at its raw state, rather than what production infrastructure brings, because they should work the same way. That NuGet package stands up the webserver in another process and you use `HttpClient` to call it, meaning that it's still making network calls (although they aren't going outbound), which covers enough of what I'm happy with. This also means that we can return the `1xx` range and test them, something that's not possible on Azure.

> > The file `src/staging.runsettings` shouldn't be include, I'm assuming it's mainly there because it's relying on the Azure hosted resource.
> 
> I wasn't sure whether to include it. It's for running the tests locally and it saves everyone trying to figure out how to set it in case they want to run locally. I can remove it if you like. Yes, it's for testing against the deployed resource, but as I said above, maybe it's a good idea to keep that (_as well as_ using `Microsoft.AspNetCore.Mvc.Testing`). It's the same resource that's defined in `staging.yml`. BTW that was defined by you, but didn't exist, so I created it.

Yeah, that resource isn't up to date anyway (presently there isn't a staging deployment...).

> > Rather than creating a class for the status codes, I'd like to find a way that we can reuse the classes from the main web project, so we don't have the duplication of code.
> 
> That's possible, but then the tests are using the code that they're supposed to be testing, so if the code breaks then the tests will still pass because they're using the broken code.

From a test validation standpoint, I'm find with _I request a `200`, I get back a `200`, with the body/headers/etc. as described in code_. If the response body/headers/etc. aren't aligned with the HTTP spec, well, that's a different problem and beyond the scope of testing, I'm really only interested in that the custom action result works the way that is expected and returns what is defined in the code.

**Comment by neilboyd** [comment]
I updated to reuse status classes from main project.
Next I'll change it to use `Microsoft.AspNetCore.Mvc.Testing`.

**Comment by neilboyd** [comment]
@aaronpowell I think I've addressed all your comments now

**Comment by aaronpowell** [comment]
Looks good, I'll see if I can get to it properly over the next week

**Comment by neilboyd** [comment]
> Yeah, that resource isn't up to date anyway (presently there isn't a staging deployment...).

I made `staging.yml` work as intended, but if you're not interested in a staging environment then it's just an annoyance now and you could delete this file. Or create the resource - that's no big deal - but if you're not going to use it then there's no point.

**Comment by neilboyd** [comment]
Hi @aaronpowell 
I'm sure you're busy with other things, but any chance you could have a look at this. I can delete `staging.yml` if that's a blocker for you.
I was thinking about making a PR for #70 and it'd be nice to be able to include some tests.

**Comment by aaronpowell** [comment]
Apologies @neilboyd I'll have a look at this tomorrow

**Comment by aaronpowell** [comment]
Thanks, sorry it took so long to action, between me forgetting about it and then I got sick at the end of last week, but finally merged in 🎉

**Pull request merged**
